AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for stable-diffusion-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 10240

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowHeaders:
            - '*'
          AllowMethods: 
            - '*'
          AllowOrigins: 
            - '*'
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: 'rate(60 minutes)'
            Name: StableDiffusionSchedule
            Description: schedule
            Enabled: true
      Environment:
        Variables:
          TRANSFORMERS_CACHE: /tmp/.cache
          HUGGINGFACE_HUB_CACHE: /tmp/.cache
          WIDTH: 512
          HEIGHT: 512
          STRENGTH: 0.5 # 0.75
          GUIDANCE_SCALE: 7.5
          PROMPT: 'cartoon, by Makoto Shinkai'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.9-v1

Outputs:
  HelloWorldFunctionUrlEndpoint:
      Description: "HelloWorldFunction URL Endpoint"
      Value:
        Fn::GetAtt: HelloWorldFunctionUrl.FunctionUrl
